server:
  port: 8888

spring:
  datasource:
    url: jdbc:mariadb://mariadb:3307/workstation
    username: admin     # docker-compose.yml에 설정한 MARIADB_USER 값
    password: admin123 # docker-compose.yml에 설정한 MARIADB_PASSWORD 값
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      # create: 애플리케이션 시작 시 기존 테이블 삭제 후 새로 생성 (개발 초기에만 사용)
      # update: 변경된 Entity에 따라 테이블 구조 업데이트 (개발 중)
      # none: 아무것도 하지 않음 (운영 환경 권장)
      ddl-auto: update
    show-sql: true       # 콘솔에 실행되는 SQL 쿼리 표시
    properties:
      hibernate:
        format_sql: true # SQL 포맷팅