spring:
  datasource:
    # Docker Compose로 띄운 DB 컨테이너의 호스트 포트(3307)와 localhost 사용
    url: jdbc:mariadb://localhost:3307/workstation_db
    username: admin
    password: admin
    driver-class-name: org.mariadb.jdbc.Driver

    jpa:
      properties:
        hibernate.dialect: org.hibernate.dialect.MariaDBDialect

      hikari:
        connection-timeout: 60000
        initialization-fail-timeout: 300000

    server:
      port: 8889
