spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: jdbc:mariadb://mariadb:3306/workstation_db
    username: admin
    password: admin
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate # 운영 DB 스키마 보호
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect

      server:
        port: 8889