#spring:
#  datasource:
##    url: jdbc:mariadb://mariadb:3306/workstation_db
#    url: jdbc:mariadb://localhost:3307/workstation_db
#    username: admin
#    password: admin
#    driver-class-name: org.mariadb.jdbc.Driver
#
#  jpa:
#    properties:
#      hibernate.dialect: org.hibernate.dialect.MariaDBDialect
#    hibernate:
#      ddl-auto: update
#
#  hikari:
#    connection-timeout: 60000
#    initialization-fail-timeout: 300000
#
#server:
#  port: 8889

spring:
  application:
    name: spa-backend
  profiles:
    active: dev

server:
  port: 8889
